# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fec067c44008e98c440ce9c515dff5c2187e6f34f576bf3bb4846324fb3a7cd6f9f69ca3804579d33c12660e9ae2f1cc6c210f251c2d7e7d8dd26b6337664cb

test:
  secret_key_base: 5add7c56958361a5b5d5e1cc035a0cd83ef02d5f74cc82f9e0e67d8d366a0d27e3b6097871e9c43063d0eff9e75e8418f99e6652dfc48dafe04a169c8d91c0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
